program: train.py
method: random
project : project_name # your project_name
name: test_name
metric:
  goal: maximize
  name: val_pearson
parameters:
  batch_size: 
    values: [16,32,64]
  lr:
    min: 0.000001
    max: 0.00001
  epochs:
    values: [5, 10, 15]
  precision:
    values : [16,32]
  R_drop :
    values : [True,False]
  warmup_step:
    values : [0.05, 0.1, 0.15]
  drop_out:
    values : [0.05, 0.1, 0.15]
